{
    'name': 'Leads',
    'version': '1.0.0',
    'summary': 'Leads',
    'description': """
        A more detailed description of the module.
    """,
    'author': 'Ajesh',
    'website': 'https://www.yourwebsite.com',
    'category': 'Specific Category',
    'license': 'LGPL-3',
    'depends': [
        'base', 'website', 'openeducat_core', 'logic_base_17', 'hr', 'mail',
    ],
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'security/rules.xml',
        'data/re_enquiry_sequence.xml',
        'views/leads.xml',
        'views/lead_team_views.xml',
        'views/team_bulk_assign_wizard_views.xml',
        'views/source.xml',
        'views/connection.xml',
        'views/convert_lead.xml',
        'views/student.xml',
        'views/allocation.xml',
        'data/actions.xml',
        'views/invoice.xml',
        'views/re_allocation.xml',
        'views/re_enquiry_views.xml',
        'views/lead_dashboard.xml',
        'views/nurturing_dashboard.xml',
        'views/nurturing_category_views.xml',
        'data/followup_cron.xml',
        # 'views/lead_open_wizard_view.xml',
        'views/leads_schedule_wizard_view.xml',
        'views/leads_funnel_wizard_view.xml',
        'views/leads_confirm_wizard_view.xml',
        'views/res_config_settings_views.xml',
        'views/res_users_views.xml',
        'views/voxbay_call_wizard_views.xml',
        'views/lead_quality_bulk_wizard_views.xml',
        'views/lead_source_bulk_wizard_views.xml',
        'views/lead_source_campaign_bulk_wizard_views.xml',
        'views/lead_nurture_export_wizard_views.xml',
        'views/course_inter.xml',

    ],
    'assets': {
        'web.assets_backend': [
            'custom_leads/static/src/css/leads.css',
            'custom_leads/static/src/css/progress_bar.css',
            # 'custom_leads/static/src/js/progress.js',
            # 'custom_leads/static/src/js/open_lead_popup.js',
            'custom_leads/static/src/js/lead_funnel_list.js',
            'custom_leads/static/src/js/lead_followup_form_popup.js',
            'custom_leads/static/src/css/lead_dashboard.css',
            'custom_leads/static/src/js/lead_stage_dashboard.js',
            'custom_leads/static/src/xml/lead_stage_dashboard.xml',
            'custom_leads/static/src/css/nurturing_dashboard.css',
            'custom_leads/static/src/js/nurturing_dashboard.js',
            'custom_leads/static/src/xml/nurturing_dashboard.xml',
            # 'custom_leads/static/src/js/lead_popup_listener.js',

        ],
    },

    'installable': True,
    'application': True,
    'auto_install': False,
}
